--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table K_PREFERMOVIE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."K_PREFERMOVIE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTER" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"GENRE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.K_PREFERMOVIE
SET DEFINE OFF;
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (526896,'모비우스','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (675353,'수퍼 소닉 2','/8dzKn3RtPWUJRG9ymSpi423eMNV.jpg',10751);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (752623,'로스트 시티','/8kZapNBZYGJu7AUbJVBDMmQgO1D.jpg',28);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (507086,'쥬라기 월드: 도미니언','/odxdUZWZ7fBfy3ZRj063wuJnZvo.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (818397,'메모리','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',53);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (639933,'노스맨','/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',14);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (453395,'닥터 스트레인지: 대혼돈의 멀티버스','/vL5ktZauR0fZMDOHKjakb1idhuU.jpg',28);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (526896,'모비우스','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (675353,'수퍼 소닉 2','/8dzKn3RtPWUJRG9ymSpi423eMNV.jpg',10751);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (752623,'로스트 시티','/8kZapNBZYGJu7AUbJVBDMmQgO1D.jpg',28);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (507086,'쥬라기 월드: 도미니언','/odxdUZWZ7fBfy3ZRj063wuJnZvo.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (818397,'메모리','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',53);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (639933,'노스맨','/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',14);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (453395,'닥터 스트레인지: 대혼돈의 멀티버스','/vL5ktZauR0fZMDOHKjakb1idhuU.jpg',28);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (526896,'모비우스','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (675353,'수퍼 소닉 2','/8dzKn3RtPWUJRG9ymSpi423eMNV.jpg',10751);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (752623,'로스트 시티','/8kZapNBZYGJu7AUbJVBDMmQgO1D.jpg',28);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (507086,'쥬라기 월드: 도미니언','/odxdUZWZ7fBfy3ZRj063wuJnZvo.jpg',878);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (818397,'메모리','/8uiV88A5eB7PjMTtY6lQBUZ0Cpl.jpg',53);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (639933,'노스맨','/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',14);
Insert into ADMIN.K_PREFERMOVIE (ID,NAME,POSTER,GENRE) values (453395,'닥터 스트레인지: 대혼돈의 멀티버스','/vL5ktZauR0fZMDOHKjakb1idhuU.jpg',28);
