--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table K_REPORT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."K_REPORT" 
   (	"R_ID" NUMBER(5,0), 
	"REPORTSENDEMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTEDEMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTDATE" DATE, 
	"REPORTSUBJECT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTCONTENT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"REPORTMOVIEID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.K_REPORT
SET DEFINE OFF;
Insert into ADMIN.K_REPORT (R_ID,REPORTSENDEMAIL,REPORTEDEMAIL,REPORTDATE,REPORTSUBJECT,REPORTCONTENT,REPORTMOVIEID) values (122,'hoo788@gamil.com','test11@a.a',to_date('22/06/22','RR/MM/DD'),'스팸홍보/도배글입니다.','도배글 입니다.','718789');
Insert into ADMIN.K_REPORT (R_ID,REPORTSENDEMAIL,REPORTEDEMAIL,REPORTDATE,REPORTSUBJECT,REPORTCONTENT,REPORTMOVIEID) values (127,'pak5893@naver.com','pak5893@naver.com',to_date('22/06/22','RR/MM/DD'),'청소년에게 유해한 내용입니다.','근형 계정 신고','718789');
Insert into ADMIN.K_REPORT (R_ID,REPORTSENDEMAIL,REPORTEDEMAIL,REPORTDATE,REPORTSUBJECT,REPORTCONTENT,REPORTMOVIEID) values (129,'b@b.b','abc@acc.com',to_date('22/06/22','RR/MM/DD'),'스팸홍보/도배글입니다.','스팸홍보','338953');
--------------------------------------------------------
--  DDL for Index K_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."K_REPORT_PK" ON "ADMIN"."K_REPORT" ("R_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table K_REPORT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."K_REPORT" MODIFY ("R_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_REPORT" ADD CONSTRAINT "K_REPORT_PK" PRIMARY KEY ("R_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
