--------------------------------------------------------
--  파일이 생성됨 - 수요일-6월-29-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table K_SHOWS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."K_SHOWS" 
   (	"ID" NUMBER, 
	"ORIGINAL_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_COUNTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"GENRE_IDS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ORIGINAL_LANGUAGE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"OVERVIEW" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTER_PATH" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_AIR_DATE" DATE, 
	"VOTE_AVERAGE" NUMBER, 
	"VOTE_COUNT" NUMBER, 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.K_SHOWS
SET DEFINE OFF;
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (66732,'Stranger Things','US','[10765-18-9648]','en','인디애나주의 작은 마을에서 행방불명된 소년. 이와 함께 미스터리한 힘을 가진 소녀가 나타나고, 마을에는 기묘한 현상들이 일어나기 시작한다. 아들을 찾으려는 엄마와 마을 사람들은 이제 정부의 일급비밀 실험의 실체와 무시무시한 기묘한 현상들에 맞서야 한다.','/mpOQpOKdo2XJnTqRzo1lTmDNsc1.jpg',to_date('16/07/15','RR/MM/DD'),8,10831,'기묘한 이야기');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (76479,'The Boys','US','[10765-10759]','en','20만 명이 넘는 슈퍼히어로가 유명세에 취해 무모한 행동을 일삼고 부패한 세상에 슈퍼히어로와 상대조차 되지 않는 일반인으로 구성된 CIA 비밀 자경팀이 그들을 막으려 하는 이야기','/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg',to_date('19/07/25','RR/MM/DD'),8,5953,'더 보이즈');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (52814,'Halo','US','[10759-10765]','en','인류가 만들어낸 최강의 전사 ''마스터 치프''. 외계 종족으로부터 인류를 지켜내기 위해선 자신의 과거를 마주해야 한다.','/eO0QV5qJaEngP1Ax9w3eV6bJG2f.jpg',to_date('22/03/24','RR/MM/DD'),8,937,'헤일로');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60574,'Peaky Blinders','GB','[18-80]','en','제1차 세계대전 직후인 1919년 영국 버밍엄. 토마스 셸비를 주축으로 한 셸비 가문은 악명 높은 범죄 조직 "피키 블라인더스"를 이끌고 암흑가의 정상을 차지하기 위해 수단과 방법을 가리지 않는다.','/bGZn5RVzMMXju4ev7xbl1aLdXqq.jpg',to_date('13/09/12','RR/MM/DD'),8,6527,'피키 블라인더스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (92830,'Obi-Wan Kenobi','US','[10765-10759-18]','en','케노비는 "스타워즈 에피소드 3: 시스의 복수"에서 드라마틱한 인생 최악의 패배를 겪었다. 절친한 벗이자 제다이 견습생인 아나킨 스카이워커가 타락하여 사악한 시스 군주 다스 베이더가 된 것. 10년이 흐른 지금, 이야기가 시작된다.','/oy2y5oKXsjwdD4uFf6aAG4221xa.jpg',to_date('22/05/26','RR/MM/DD'),8,262,'오비완 케노비');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (120089,'SPY×FAMILY','JP','[16-35-10759-80]','ja','사람은 누구나 아무에게도 보여줄 수 없는 자신을 갖고 있다.

세계 각국이 물밑에서 치열하게 정보전을 펼치는 시대.

오스타니아와 웨스탈리스는 십수 년간에 걸쳐 냉전 상태에 있었다.

웨스탈리스의 정보국 대동과 ''WISE'' 소속의 수완가 스파이인 ''황혼'' 은 동서 평화를 위협하는 위험인물, 오스타니아의 국가통일당 총재 도노반 데스몬드의 동향을 살피기 위해 어떤 극비 임무를 수행하게 된다.

그 이름은 오퍼레이션 ''올빼미''.

임무 내용은 "일주일 이내에 가족을 만들어, 데스몬드의 아들이 다니는 명문 학교의 친목회에 잠입하라".

''황혼'' 은 정신과 의사 로이드 포저로 위장하고 가족을 만들게 된다.

하지만, 그가 만난 딸 아냐는 마음을 읽을 수 있는 초능력자, 아내 요르는 암살자였다!

3명의 이해가 일치하여 서로 정체를 숨기면서 함께 생활하게 되는데.

해프닝 연속인 임시 가족에게,  세계의 평화는 맡겨졌다...','/stMXKaZYy5bhZII72F9yMl4AYxJ.jpg',to_date('22/04/09','RR/MM/DD'),8,204,'스파이 패밀리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (92749,'Moon Knight','US','[10759-10765-9648]','en','온화한 성격의 기념품점 직원, 스티븐 그랜트는 일시적 기억 상실과 또 다른 생의 기억으로 힘들어하는 도중 자신이 해리성 정체 장애를 갖고 있다는 것과 마크 스펙터라는 용병과 몸을 공유한다는 사실을 알게 된다. 스티븐/마크에게 적이 모여들자 둘은 얽힌 정체성을 넘나들며 이집트의 강력한 신들 간의 위험한 미스터리에 빠져든다.','/h9fjtMeoaI3LrW8avMZoJPoniLZ.jpg',to_date('22/03/30','RR/MM/DD'),8,1040,'문나이트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (158415,'Pantanal','BR','[18-10766]','pt',null,'/wRzDupqEtggcrs9032yNgGNxDA.jpg',to_date('22/03/28','RR/MM/DD'),4,21,'Pantanal');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (49608,'Canım Annem','TR','[18-10766]','tr',null,'/pPjyZWvaLzu2MRllG64p6eyQyre.jpg',to_date('22/02/14','RR/MM/DD'),7,9,'Canım Annem');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (99966,'지금 우리 학교는','KR','[10759-18-10765]','ko','좀비 바이러스 발생의 시발점이 된 고등학교. 이곳에 갇힌 학생들은 필사적으로 탈출구를 찾아야만 한다. 그렇지 않으면 감염되어 좀비가 될 뿐.','/d9yefq8dNke4UbuqStBtUcO9TxD.jpg',to_date('22/01/28','RR/MM/DD'),8,2211,'지금 우리 학교는');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1416,'Grey''s Anatomy','US','[18]','en','시애틀에 있는 병원 의사들의 삶에 대한 이야기. 의사로서의 감정과 개인적인 감정에 대한 묘사가 적절히 조화를 이루어 그려진다. 인턴이지만 결국 레지던트가 되는 메러디스 그레이는 시애틀 병원의 동료 의사들과 함께 사적, 직업적인 열정에 휩쓸리는 자신을 발견한다.','/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg',to_date('05/03/27','RR/MM/DD'),8,8084,'그레이 아나토미');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (202728,'Bisik-Bisik Gelora','MY','[18]','ms',null,'null',to_date('22/05/21','RR/MM/DD'),0,0,'Bisik-Bisik Gelora');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (95171,'Prehistoric Planet','GB','[99]','en','존 패브로와 살아 있는 지구 제작자들이 만든 이 장대한 다큐멘터리에서는 전례 없는 경이로움을 경험할 수 있다. 웅장한 공룡과 특별한 생물들이 땅과 바다, 하늘을 누볐던 6,600만 년 전으로 거슬러 올라간다.','/yMdFsHKp4YX2CUkAQcZswxXDuoe.jpg',to_date('22/05/23','RR/MM/DD'),8,104,'선사시대: 공룡이 지배하던 지구');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (80020,'スーパードラゴンボールヒーローズ','JP','[16-10759-10765]','ja','다른 차원의 사이야인들의 전투','/8jq6xv5c1WK7KAPOXCsodm8eUxp.jpg',to_date('18/07/01','RR/MM/DD'),7,2582,'드래곤볼 히어로즈');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (154911,'Além da Ilusão','BR','[18-10766]','pt',null,'/8BzuwDAMamf5TX4TepbDDEq7ima.jpg',to_date('22/02/07','RR/MM/DD'),6,10,'Além da Ilusão');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (63174,'Lucifer','US','[80-10765]','en','지긋지긋한 지옥 생활을 청산하고 은퇴를 선언한 악마. LA로 와 나이트클럽을 열고 인생을 즐기던 어느 날 강력계 형사를 만나면서 새로운 삶을 살기 시작한다.','/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg',to_date('16/01/25','RR/MM/DD'),8,11965,'루시퍼');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (92782,'Ms. Marvel','US','[10765-10759-35]','en','저지시티에 살고 있는 무슬림계 미국 10대 소녀인 카말라 칸 이야기를 다룬다. 게임에 죽고 살며 열렬한 팬 픽션 작가인 카말라는 슈퍼 히어로 광팬이기도 한데, 특히 캡틴 마블에 대한 팬심은 상상을 초월한다. 카말라는 학교뿐만 아니라 집에서도 떠도는 느낌을 받고는 하지만, 결국 자신이 우러러보던 영웅처럼 초능력을 얻게 되는데... 초능력이 있으면 살기 편한 거 아닌가?','/5K0F6lYosnp162drTXTJD9Pisp6.jpg',to_date('22/06/08','RR/MM/DD'),8,94,'미즈 마블');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (79028,'Power Couple Brasil','BR','[10764]','pt',null,'/s0gqncO6khWQj4QzLpQ7z4h3lYZ.jpg',to_date('16/04/12','RR/MM/DD'),4,9,'Power Couple Brasil');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (154300,'Euronews Hoy','ES','[10763]','es',null,'/ujeIjo0GTRbFJcgjhgFZda78A90.jpg',to_date('19/01/28','RR/MM/DD'),5,2,'Euronews Hoy');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60735,'The Flash','US','[18-10765]','en','낙뢰 사고의 후유증으로 초인적인 스피드를 가지게 된 CSI 수사관 배리 앨런이 범죄에 맞서 싸우는 영웅 플래시로 활약하는 이야기를 그리는 드라마','/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg',to_date('14/10/07','RR/MM/DD'),7,9686,'플래시');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (62715,'ドラゴンボール超（スーパー）','JP','[16-10759-10765]','ja','오공은 사상 최대의 강적인 마인 부우와의 처절한 사투 끝에 마인 부우를 제압하는데 성공하고, 지구에는 다시 평화가 찾아온다. 그렇게 평화로운 나날을 보내던 중, 오랜 잠에서 깨어난 파괴의 신 비루스가 등장하고, 과거 우주의 제왕으로 불리며 사람들을 공포에 떨게 했던 프리저마저 부활하는 등, 오공 일행을 위협하는 일들이 끊임없이 발생한다. 거기에 지구 주변에서 갑자기 별들이 사라지는 기묘한 현상까지 일어나기 시작하면서 지구에는 또 다시 불길한 위기감이 감돈다. 오공 일행은 이 위기를 타파하고 지구의 평화를 지키기 위해 다시 힘을 모아 일어서기로 하는데...','/kXmsg1FhP3oywFHItoVqv109Drk.jpg',to_date('15/07/05','RR/MM/DD'),8,3964,'드래곤볼 슈퍼');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (12971,'ドラゴンボールゼット','JP','[16-10765-10759]','ja','흥미진진한 드래곤 볼! 계속되는 이야기! 성장한 손오공이 치치와 결혼하여 손오반이라는 아들까지 둔 모습을 보여주고 있다. 어느 날 우주로부터 형 라데츠가 찾아와 지구를 멸망시키려고 하며 손오공에게 동참할 것을 설득한다. 하지만, 자신의 설득이 먹혀들지 않자 조카인 오반을 납치한다. 오공과 피콜로가 합심하여 라데츠를 물리치지만, 오공도 죽어버리는 사태가 발생한다. 지구를 위해, 그리고 우주를 위해 싸우는 Z 용사들!','/f2zhRLqwRLrKhEMeIM7Z5buJFo3.jpg',to_date('89/04/26','RR/MM/DD'),8,3213,'드래곤볼 Z');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2734,'Law & Order: Special Victims Unit','US','[80-18]','en','추악한 성범죄를 수사하는 뉴욕 경찰 성범죄전담수사반의 활약을 그린 드라마.','/ydSvHgksuB8Ix0V05QEZBKrnIcg.jpg',to_date('99/09/20','RR/MM/DD'),7,2896,'로 앤 오더: 성범죄 전담반');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (18165,'The Vampire Diaries','US','[18-10765]','en','L. J. 스미스의 뱀파이어 다이어리 소설 시리즈 원작. 뉴욕 외곽도시, 미스틱 폴즈의 한 고등학교를 배경으로 두 뱀파이어 형제 스테판과 데미언, 그리고 인간 소녀 엘레나의 로맨스를 그린다.','/aBkVgChtyyJaHyZh1gfd8DbzQon.jpg',to_date('09/09/10','RR/MM/DD'),8,7289,'뱀파이어 다이어리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (65334,'Miraculous, les aventures de Ladybug et Chat Noir','FR','[10759-16-10762]','fr','프랑스 파리를 배경으로, 백인 아버지와 중국인 어머니 사이에서 태어난 중국계 프랑스인 소녀, 마리네트 청이 ‘레이디버그’로 변신해 악당으로부터 파리를 지키는 내용이다.','/evDCpiQqAvEnR14exVUqnbC0W3U.jpg',to_date('15/10/19','RR/MM/DD'),8,3701,'미라큘러스 레이디버그');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (103516,'Star Trek: Strange New Worlds','US','[10765]','en','새로운 우주, 새로운 모험. 엔터프라이즈호의 새로운 항해가 시작된다.','/iwIdajr5Y4zq2ibvq75VnDAJBr.jpg',to_date('22/05/05','RR/MM/DD'),8,80,'스타 트렉: 스트레인지 뉴 월드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (128010,'Bienvenidos a Edén','ES','[10759-10765-18]','es','당신은 행복한가?  이 질문을 통해 소아, 그리고 소셜 미디어를 활발하게 사용하는 매력적인 젊은 남녀 넷이 역사상 가장 특별한 파티에 초대받는다. 새로운 음료 브랜드가 비밀의 섬에서 마련한 이 파티는 흥미진진한 모험으로 출발해 이내 삶의 여행으로 바뀐다. 하지만 낙원은 겉으로 보이는 것과는 다른 곳...  에덴에 오신 것을 환영합니다.','/iZSmq8iOupIIirR7rsvLqp5Ghi2.jpg',to_date('22/05/06','RR/MM/DD'),7,82,'웰컴 투 에덴');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1402,'The Walking Dead','US','[10759-18-10765]','en','2010년 10월 AMC에서 방영을 시작한 좀비 아포칼립스물. 조지아 주의 보안관 릭은 범인 검거 중에 총상을 입고 혼수상태에 빠진다. 어느 날 혼수 상태에서 깨어난 릭은 폐허가 되어 버린 세상이 좀비들로 뒤덮여 있는 것을 발견한다. 쇠약해진 몸으로 병원을 빠져나온 릭은 워커라고 불리는 좀비들을 피해 생존자를 찾아다니고, 마을의 생존자 모건 부자의 도움을 받아 건강을 회복한 후 아내 로리와 아들 칼을 찾으러 애틀랜타로 떠나지만, 릭을 반긴 것은 셀 수 없이 많은 워커 무리들. 간신히 전차 내부로 피신한 릭을 백화점에 숨어있던 생존자 일행이 도와서 겨우 전차에서 빠져나오는데...','/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg',to_date('10/10/31','RR/MM/DD'),8,13134,'워킹 데드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (456,'The Simpsons','US','[10751-16-35]','en','1989년 12월 FOX에서 방영을 시작한 애니메이션. 미국의 스프링필드를 배경으로 먹는 걸 유난히 밝히고 게으르며 독특한 성격의 가장 호머, 항상 사고만 치고 다니는 남편과 아이들의 뒤치다꺼리를 도맡아 하는 엄마 마지, 하루라도 장난을 치지 않고 넘어가는 날이 없는 장난꾸러기 아들 바트, 나이에 비해 꽤나 어른스럽고 똑똑한 리사, 그리고 말은 한마디도 못하지만 의외의 대활약을 보여주는 막내 메기 등 각각의 개성 만점 가족 구성원들이 펼치는 극적인 하루하루를 그리고 있다.','/sLTAEFtjentQ5satiGdmv7o2f1C.jpg',to_date('89/12/17','RR/MM/DD'),8,7916,'심슨 가족');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (71712,'The Good Doctor','US','[18]','en','자폐증을 가진 젊은 외과 의사가 명문 병원에 들어가게된다. 이에 사람들과 소통하지 못하는 의사가 사람의 목숨을 구할 수 있을 까 하는 의문이 제기되는데...','/53P8oHo9cfOsgb1cLxBi4pFY0ja.jpg',to_date('17/09/25','RR/MM/DD'),8,10564,'굿 닥터');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (158691,'My Little Pony: Make Your Mark','US','[16-10762]','en',null,'/jfmQPOHnuARC7YxGYC1vMMph3vp.jpg',to_date('22/05/26','RR/MM/DD'),8,21,'My Little Pony: Make Your Mark');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (44953,'El señor de los cielos','MX','[80-18-10766]','es',null,'/Ag7VUdnrRz5Qpq3Yn3E5OCvFnu0.jpg',to_date('13/04/15','RR/MM/DD'),7,1887,'El señor de los cielos');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1399,'Game of Thrones','US','[10765-18-10759]','en','2011년 4월 HBO에서 방영을 시작한 판타지물. 조지 R.R. 마틴의 얼음과 불의 노래를 원작으로 한다. 웨스테로스 대륙의 7개의 국가와 하위 몇 개의 국가들로 구성된 연맹 국가인 칠 왕국의 통치권, 철 왕좌를 차지하기 위한 싸움을 그려낸 드라마이다. 왕좌를 차지하기 위한 귀족 가문의 다툼 외에도 북부에 존재하는 미지의 위협인 백귀, 그리고 15년 전에 내전으로 인해 살해된 왕의 딸인 대너리스 타르가르옌이 자신이 추방당한 웨스테로스를 향해 왕권 회복을 도전하는 이야기가 함께 들어있다.','/lxfllsQQ32gKglUxrM61WaFeNcy.jpg',to_date('11/04/17','RR/MM/DD'),8,18024,'왕좌의 게임');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (93405,'오징어 게임','KR','[10759-9648-18]','ko','빚에 쫓기는 수백 명의 사람들이 서바이벌 게임에 뛰어든다. 거액의 상금으로 새로운 삶을 시작하기 위해. 하지만 모두 승자가 될 순 없는 법. 탈락하는 이들은 치명적인 결과를 각오해야 한다.','/yACIAqAkSLkX4coHafpyLWAtQjw.jpg',to_date('21/09/17','RR/MM/DD'),7,10802,'오징어 게임');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (95057,'Superman & Lois','US','[10765-18]','en','세계에서 가장 유명한 슈퍼히어로와 코믹북에서 가장 유명한 저널리스트의 이야기','/vlv1gn98GqMnKHLSh0dNciqGfBl.jpg',to_date('21/02/23','RR/MM/DD'),8,1709,'슈퍼맨과 로이스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2224,'The Daily Show with Trevor Noah','US','[10763-35]','en',null,'/f3aNNMYYFXK6dAM1Ly4V0cljIvu.jpg',to_date('96/07/22','RR/MM/DD'),6,389,'The Daily Show with Trevor Noah');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (196749,'The Quest','US','[10765-10759-18]','en','"퀘스트"는 에버렘이라는 가상의 판타지 세계에 8명의 실제 십 대 아이들을 떨어뜨리고, 그들이 고대의 예언에 따라 왕국을 구하는, 획기적인 몰입형 경연 시리즈이다. 8개의 에피소드로 구성된 시리즈 내내 이 영웅들은 성, 왕족, 신비로운 운명의 여신들, 파괴와 권력을 노리는 사악한 마법사가 실제로 존재하는 판타지 세계에 푹 빠진다.','/nNQvnKK6TZNF6ibEzuCo6OLNdKz.jpg',to_date('22/05/11','RR/MM/DD'),6,24,'더 퀘스트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (136166,'Lang Leve de Liefde','NL','[10764]','nl',null,'/9lpvvzEl5kViIc2vUJG4QKzj2ds.jpg',to_date('20/01/20','RR/MM/DD'),0,0,'Lang Leve de Liefde');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60797,'Scorpion','US','[10759-18-80]','en','스콜피온이라 불리는 천재 월터 오브라이언의 실화를 다룬 드라마로, 그가 또다른 천재들을 고용해 그들과 함께 이 세상에 존재하는 복잡한 문제들을 해결해나가는 이야기','/u80AJrwINGOeQElFd2fTOUaJyXY.jpg',to_date('14/09/22','RR/MM/DD'),8,3418,'스콜피온');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (110492,'Peacemaker','US','[10759-10765-18]','en','DC 확장 유니버스의 피스메이커가 주인공인 HBO 맥스 드라마. DC 확장 유니버스 최초의 드라마기도 하다.

더 수어사이드 스쿼드의 스핀오프로, 더 수어사이드 스쿼드의 쿠키 영상부터 그대로 이어진다.','/hE3LRZAY84fG19a18pzpkZERjTE.jpg',to_date('22/01/13','RR/MM/DD'),8,1779,'피스메이커');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (30810,'Pointless','GB','[10764]','en',null,'/vhKxgbh4QvnBFU1jRYSBiizWpDg.jpg',to_date('09/08/24','RR/MM/DD'),6,22,'Pointless');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (195623,'Mi Tío','ES','[35-18]','es',null,'/sDPNwSe63WACVlHap7un6AgbqgO.jpg',to_date('22/03/25','RR/MM/DD'),7,32,'Mi Tío');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (71914,'The Wheel of Time','US','[10765-18]','en','마을에 처음 보는 강력한 여성이 나타나 다섯 청년의 인생을 송두리째 바꿔놓을 주장을 한다. 그들 중 한 사람이 고대 예언에 나온 빛과 어둠의 균형을 영원히 바꿔놓을 힘을 가진 아이라는 것. 청년들은 세계의 운명을 걸고 이 낯선 여성과 서로를 믿을지 결정해야 한다. 어둠의 존재가 구속에서 벗어나 최후의 싸움이 시작되기 전에.','/mpgDeLhl8HbhI03XLB7iKO6M6JE.jpg',to_date('21/11/18','RR/MM/DD'),7,1416,'시간의 수레바퀴');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1911,'Bones','US','[80-18]','en','워싱턴 D.C.의 제퍼소니안 재단의 연구소 소속 법인류학자인 템퍼런스 브레넌 박사와 FBI 워싱턴 지국 요원인 실리 부스, 그리고 브레넌 박사의 팀이 뼈만 남다시피한 시신을 조사해 해결하는 내용으로 실제 법인류학자인 ''캐시 라익스''의 소설을 각색해 제작되었으며 국내에도 ''본즈''라는 제목으로 원작 소설 시리즈가 발매되었다.','/24Mi1oDrdc1zbHju7FVHJA4sgYt.jpg',to_date('05/09/13','RR/MM/DD'),8,2452,'본즈');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (88329,'Hawkeye','US','[10759-18]','en','2021년 11월 Disney+에서 방영을 시작한 미니시리즈. 어벤져스이던 클린트 바튼(일명 호크아이)에게 블립 이후 뉴욕을 배경으로 일어나는 일을 다룬 오리지널 시리즈로서, 클린트는 크리스마스를 맞이해 가족에게 돌아가고자 하지만, 과거와 엮인 위험을 감지하고는 마지못해 자신의 열혈 팬이자 활 솜씨가 뛰어난 22살 케이트 비숍과 함께 범죄 음모 수사에 나서게 된다.','/tvzOzfQz2M2DLXNkg4gNbcYEOc0.jpg',to_date('21/11/24','RR/MM/DD'),8,2039,'호크아이');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (117821,'WeCrashed','US','[18]','en','실제 사건에서 영감을 받은 이야기, 그리고 그 모든 중심에는 사랑이 있다. ''위워크''는 10년도 안 되어 단 하나의 공유 사무실에서 470억 달러 가치의 국제 브랜드로 성장했으나, 채 1년도 안 되어 400억 달러를 잃었다. 과연 무슨 일이 있었던 걸까?','/ch28OlP49Hr2ftNGhftr3Mix1BU.jpg',to_date('22/03/18','RR/MM/DD'),7,43,'우린폭망했다');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2051,'The Price Is Right','US','[]','en',null,'/6m4uYFAJwkanZXd0n0HUQ0lYHLl.jpg',to_date('72/09/04','RR/MM/DD'),6,55,'The Price Is Right');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1434,'Family Guy','US','[16-35]','en','로드 아일랜드의 쿼호그라는 도시에서 살아가는 가장 피터, 아내 로이스, 장녀 메그, 차남 크리스, 막내 스튜이, 개 브라이언으로 이루어진 그리핀 가족과 그 주변인들의 일상을 다루고 있다.','/eWWCRjBfLyePh2tfZdvNcIvKSJe.jpg',to_date('99/01/31','RR/MM/DD'),7,3273,'쇼킹 패밀리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (67335,'Sin senos sí hay paraíso','CO','[10759-80-18-9648]','es',null,'/7lBJ6lOS0uQqsH13U9iMTikawQS.jpg',to_date('16/07/19','RR/MM/DD'),7,2554,'Sin senos sí hay paraíso');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (94722,'Tagesschau','DE','[10763]','de',null,'/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg',to_date('52/12/26','RR/MM/DD'),6,9,'타게스샤우');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (74851,'Beyond Stranger Things','US','[10767]','en','출연진과 제작진이 들려주는 《기묘한 이야기 2》의 모든 것. 구상, 제작 비화부터 각 인물의 캐릭터 해석까지, 기묘한 세계의 늪으로 초대한다. "스포일러 나갑니다!"','/pixcHLGqLYuMMHdRHmIC0oLsgbp.jpg',to_date('17/10/27','RR/MM/DD'),7,56,'기묘한 이야기의 궁금한 이야기');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (71446,'La Casa de Papel','ES','[80-18]','es','1명의 천재, 8명의 공범, 철저히 준비한 세기의 강도. 스페인 조폐국에서 인질극까지 벌인 이들은 과연 포위 경찰을 따돌리고 거액의 돈과 함께 달아날 수 있을까?','/e4IK8bunUl8OiYyebFUuRKKHD4m.jpg',to_date('17/05/02','RR/MM/DD'),8,16391,'종이의 집');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (80240,'La Reina del Flow','CO','[18]','es',null,'/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg',to_date('18/06/12','RR/MM/DD'),8,1328,'The Queen of Flow');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (66203,'Soy Luna','AR','[10766-10762]','es',null,'/mK1egVq2qMLMw4HIREUXuihKj9g.jpg',to_date('16/03/14','RR/MM/DD'),7,923,'Soy Luna');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (128252,'El cartel de los sapos: El origen','CO','[80-10766]','es',null,'/AoOsbKi4sZYU42FmIE1aap770nL.jpg',to_date('21/07/28','RR/MM/DD'),7,252,'El cartel de los sapos: El origen');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (34524,'Teen Wolf','US','[10765-18]','en','어느 날 갑자기 늑대인간이 되어버린 후, 우정과 사랑을 지키며 스스로 살아남기 위해서 싸우는 고등학생 스캇의 이야기. 1985년 제작된 동명 영화를 리메이크한 작품.','/8Ij1O2nU8exLgwPXU8Eo6PZdCDC.jpg',to_date('11/06/05','RR/MM/DD'),8,3246,'틴 울프');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (16286,'Yo soy Betty, la fea','CO','[10766-35-18]','es',null,'/iEBOiXiDGaxVR6w8aKgG5MEusuO.jpg',to_date('99/10/25','RR/MM/DD'),8,2785,'Yo soy Betty, la fea');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (44006,'Chicago Fire','US','[18]','en','시카고의 한 소방서를 배경으로 각자의 사연을 지닌 소방관들의 숭고한 직업정신을 그린 드라마.','/yrV8eSwhCkMAJVZUK65PXTfYOqq.jpg',to_date('12/10/10','RR/MM/DD'),8,1735,'시카고 파이어');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (966,'Hollyoaks','GB','[10766]','en',null,'/bpmLMZP3M1vLujPqHnOTnKVjRJY.jpg',to_date('95/10/23','RR/MM/DD'),5,44,'홀리오크');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60059,'Better Call Saul','US','[80-18]','en','브레이킹 배드의 스핀오프. 베터 콜 사울 (Better call Saul) 이라는 제목은 브레이킹 배드에서 등장하는 사울 굿맨의 변호사 광고 슬로건에서 따왔다. 2002년을 배경으로 삼류 변호사 지미 맥길이 악덕 변호사 사울 굿맨으로 변하게 되는 과정을 그린다.','/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg',to_date('15/02/08','RR/MM/DD'),8,2823,'베터 콜 사울');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (12637,'Rebelde','MX','[35-10766-18]','es',null,'/iehrrb9CmYCiV1hXp5pdGQQmGNe.jpg',to_date('04/10/04','RR/MM/DD'),8,4732,'Rebelde');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (119316,'वागले की दुनिया','IN','[35-18-10751]','hi',null,'/jKonm6Q3vw51Ytd4y7bJ70xJT7l.jpg',to_date('21/02/08','RR/MM/DD'),5,4,'वागले की दुनिया');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (9027,'Rebelde Way','AR','[10766-18]','es',null,'/wu4Vi93RxaE1kkFM5ClmcVzkIby.jpg',to_date('02/05/27','RR/MM/DD'),7,269,'Rebelde Way');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (155645,'Señorita 89','CL','[18]','es',null,'/g97jEpwPk8kaj3xjkRTyG5DllZm.jpg',to_date('22/02/27','RR/MM/DD'),7,12,'Señorita 89');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (77169,'Cobra Kai','US','[10759-18]','en','1984년 가라데 토너먼트에서 다니엘 라루소에게 충격의 패배를 당한 조니 로렌스는 이후 인생이 완전 꼬이기 시작하였다.  여자 친구는 도망가고 하는 일마다 다 망하고 급기야 해고까지 당하게 된다. 하지만 다니엘 라루소는 그날 이후 승승장구 지역의 유명한 사업가로 성공하며 어느덧 조니의 원수이자 질투의 대상으로 떠오르게 된다. 조니는 마지막 보루로 코브라 카이라는 가라데 도장을 차리게 되고 첫 수제자인 미구엘을 훈련시켜 조니의 수제자와 대결 시키게 되는데...','/5qMupAz4A9EN5Rutrkmov45mNXZ.jpg',to_date('18/05/02','RR/MM/DD'),8,4519,'코브라 카이');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1622,'Supernatural','US','[18-9648-10765]','en','어린 시절, 샘과 딘은 정체를 알 수 없는 악마의 힘의 의해 어머니를 잃는다. 그로 인해, 그들의 아버지는 자식들을 헌터로 키우며, 미국 각지에 흩어져 있는 초자연적인 악과 괴물들을 처치하는 법을 가르친다.

이제 두 윈체스터 형제들은 67년형 쉐비 임팔라에 몸을 싣고 미전역을 가로지르며 그들과 마주치는 모든 초자연적인 위협들을 처리해나가기 시작하는데...','/dpkz4yiXoaYvYP2WoRP09UmrAh6.jpg',to_date('05/09/13','RR/MM/DD'),8,5972,'수퍼내추럴');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (135647,'2 Good 2 Be True','PH','[35-18]','tl',null,'/2Wf5ySCPcnp8lRhbSD7jt0YLz5A.jpg',to_date('22/05/16','RR/MM/DD'),9,16,'2 Good 2 Be True');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (118011,'Dragon Ball Absalon','Unknown','[]','en',null,'/xs1BRXnY5kStzwdxyrl2HYJOJCq.jpg',to_date('12/11/30','RR/MM/DD'),4,12,'Dragon Ball Absalon');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (158916,'Pálpito','CO','[10766-9648]','es','아내를 살해한 장기 매매단에 기필코 복수하겠다는 의지를 불태우는 한 남자. 그는 아내의 심장을 이식받은 여자와 인연을 맺게 된다.','/jHV0cRQQSBi2juHsvhOOosKHGJ8.jpg',to_date('22/04/20','RR/MM/DD'),8,82,'예감');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (154521,'The Kardashians','US','[10764]','en','우리가 열광하는 가족들이 새로운 시리즈로 찾아와 그들의 삶을 여과 없이 보여준다. 크리스, 코트니, 킴, 클로이, 켄달 그리고 카일리가 다시 카메라 앞으로 돌아와 헤드라인 뒤에 숨겨진 진실을 밝힌다.','/oo8aunWuZxktoZmPaNqObmgxuxs.jpg',to_date('22/04/14','RR/MM/DD'),8,787,'카다시안 패밀리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (117067,'รักโคตรร้าย สุดท้ายโคตรรัก','TH','[18-10759]','th','【언컷(Uncut) 버전인 "라 포르테(La Forte)" VIP 한정 공개! 화제의 태국 드라마를 한글자막으로 시청하세요~】 형제의 희망과 꿈을 짊어진 초라한 웨이터, 포르쉐는 마피아의 세계에 발을 들이게 된다. 그는 강제로 마피아 집안의 보디가드가 되고, 이로 인해 문제만 더 많이 생긴다. 갈등의 씨앗은 킨이었지만, 이들은 고난과 시련을 함께 할수록 더 가까워진다. 두 사람 사이에는 뜨거운 감정이 생기고 곧 서로 사랑하게 된다. 포르쉐는 종잡을 수 없는 미스터리한 사건들에 얽히는데, 모두 부모님의 사망에 연관된 것이었고, 유언장이 중요한 변수가 되는데...','/fT3zPHX0EQJSxTbSWXnvLvBjZ6l.jpg',to_date('22/04/02','RR/MM/DD'),8,18,'킨포르쉐 더 시리즈 : 라 포르테');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (62348,'A Konyhafőnök','HU','[]','hu',null,'/1CoHXUTSS3IPN41pgxlvTfcVuu4.jpg',to_date('14/09/01','RR/MM/DD'),7,1,'A Konyhafőnök');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (69050,'Riverdale','US','[80-18-9648]','en','평화로운 소도시 리버데일에서 살아가는 아치와 친구들이 복잡한 연애, 섹스, 학교생활과 가족사를 헤쳐나간다. 파고들수록 수렁으로 빠져드는 리버데일의 미스터리.','/6zBWSuYW3Ps1nTfeMS8siS4KUaA.jpg',to_date('17/01/26','RR/MM/DD'),8,12652,'리버데일');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (37680,'Suits','US','[18]','en','뜻밖의 행운일까, 아니면 뛰어난 재능일까. 뉴욕의 거대 로펌에 들어간 대학 중퇴 청년. 엘리트 변호사와 의기투합한 그가 시시하고 따분한 세상을 상대로 소송을 건다.','/lvYWwQj89ioSk9WzhC1KEujmpWa.jpg',to_date('11/06/23','RR/MM/DD'),8,3495,'슈츠');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1900,'LIVE with Kelly and Ryan','US','[10767]','en',null,'/hBkyypWN3EcOzkozatiCm5VeaG.jpg',to_date('88/09/05','RR/MM/DD'),4,20,'LIVE with Kelly and Ryan');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (118663,'The Man Who Fell to Earth','US','[10765]','en',null,'/p1aBjGkyG25ADy4xu69joNMV3eQ.jpg',to_date('22/04/24','RR/MM/DD'),8,33,'지구에 떨어진 사나이');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (62286,'Fear the Walking Dead','US','[10759-18]','en','2015년 8월 AMC에서 방영을 시작한 좀비 좀비 아포칼립스물. 인기 시리즈 워킹 데드의 스핀오프 작품으로, 본편과 달리 좀비 사태가 벌어진 최초의 시점에서 당황하며 어쩔 줄 몰라하던 사람들이 점차 적응해 가는 이야기를 다루고 있다. 폐쇄된 교회에서 약에 취한 채 깨어난 닉은 함께 마약을 하던 글로리아가 사라지자 그녀를 찾기 위해 아래층으로 내려간다. 그곳에서 피와 시체들이 널부러져 있는 사이에서 글로리아가 시체를 뜯어먹고 있는 모습을 보게 된다. 겁에 질려 교회 밖으로 도망치다가 차에 치여 병원에 실려간 닉은 마약 중독 치료 권고를 받고, 자신이 본 것을 얘기하지만 정신병으로 오해 받는다.','/zyshFjmlDXSzfns2Qk81cfIFfPP.jpg',to_date('15/08/23','RR/MM/DD'),7,4151,'피어 더 워킹 데드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (157171,'How to Move On in 30 Days','PH','[35]','tl',null,'/2cLWJiDOZvhoIaX2r2Zb78K66JQ.jpg',to_date('22/04/04','RR/MM/DD'),2,1,'How to Move On in 30 Days');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1396,'Breaking Bad','US','[18]','en','2008년 1월 AMC에서 방영을 시작한 범죄 스릴러. Breaking Bad는 막가기를 뜻하는 미국 남부 지방의 속어이다. 한때 노벨화학상까지 바라 볼 정도로 뛰어난 과학자였던 고등학교 화학 교사 월터 화이트는 자신의 50세 생일 날에 폐암 3기 진단을 받는다. 어느 날 동서와 함께 마약 단속 현장을 참관한 그는 현장에서 달아나는 옛 제자 제시를 발견한다. 뇌성마비에 걸린 고등학생 아들과 임신한 아내를 위해 제시에게 동업을 제의한 월터는 자신의 화학지식을 이용해 전례없는 고순도 고품질의 메스암페타민을 제조한다.','/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',to_date('08/01/20','RR/MM/DD'),8,8841,'브레이킹 배드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (89491,'America Says','US','[10751]','en',null,'/cNZTNrWxc02moLzn3NYZqowyJdU.jpg',to_date('18/06/18','RR/MM/DD'),4,11,'America Says');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (46260,'ナルト','JP','[16-10759-10765]','ja','<주간 소년 점프>에 연재되면서 폭발적인 인기를 모았던 ''나루토''를 애니메이션으로 만들었다. 한국에서도 단행본이 나와 많은 인기를 얻고 있다. 나루토와 동료들이 닌자가 되기 위한 모험을 떠나는 흥미진진한 작품. 

닌자 마을 중 하나인 나뭇잎 마을. 매일같이 장난만 치며 공부도 뒤쳐져서 졸업조차 불안하기만 한 문제아 나루토. 그런 그이지만 마을에서 제일 가는 닌자, ''호카게''가 되고 싶다는 커다란 꿈을 지니고 있다. 하지만, 자신의 출생의 비밀을 안 나루토는 결의를 새롭게 다지고 같은 학교 학생인 사스케, 사쿠라와 함께 닌자로서의 첫 발을 내딛게 된다.','/mErFfyQuQ9kkbsR30d8CkZf0Z6s.jpg',to_date('02/10/03','RR/MM/DD'),8,4563,'나루토');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (115626,'Irma Vep','US','[35-18]','en',null,'/gVST8KoYxV8A0ZtlitzEaKeE5L2.jpg',to_date('22/06/06','RR/MM/DD'),7,11,'이마 베프');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (85552,'Euphoria','US','[18]','en','고등학생들의 마약, 섹스, 폭력, 트라우마 그리고  SNS 세상 속에서 벌어지는 사랑과 우정 이야기','/lRsDSuj98WQfXBCV44xMoG0G29M.jpg',to_date('19/06/16','RR/MM/DD'),8,7825,'유포리아');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (197189,'Cara e Coragem','BR','[35-10759-10766]','pt',null,'/8CXbCCGiJxi4AXPBQ1QPrehMIGG.jpg',to_date('22/05/30','RR/MM/DD'),0,0,'Cara e Coragem');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (11250,'Pasión de gavilanes','CO','[18]','es',null,'/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg',to_date('03/10/21','RR/MM/DD'),7,1819,'Pasión de gavilanes');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1408,'House','US','[18-9648]','en','2004년 11월 FOX에서 방영을 시작한 미스터리 의학 시리즈. 프린스턴 플레인즈보로 대학병원의 진단의학과 과장인 그레고리 하우스는 환자들을 성심성의껏 돌보는 데는 영 꽝인 의사. 사사건건 병원 원장인 리사 커디와 부딪히는 그는 못된 매너와 그 매너를 더욱 돋보이게 하는 외모로 유명하지만, 또한 창조적인 생각과 결점없는 의학적 본능을 유감없이 발휘하는 최고의 의사이기도 하다. 천재적인 분석능력을 갖춘 전염병 전문의로서 그가 이제 인명을 살리기 위한 흥미롭고 미스터리한 의학의 퍼즐을 풀어간다.','/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg',to_date('04/11/16','RR/MM/DD'),8,4632,'하우스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (4057,'Criminal Minds','US','[80-18-9648]','en','FBI 프로파일러로 구성된 정예 팀이 미국에서 가장 뒤틀린 범죄자들의 심리를 분석하고, 범죄를 또 저지르기 전에 다음 수를 예측한다. 팀원들은 함께 성장하며, 이 행동 분석팀은 전문 지식으로 범죄자의 동기를 찾아내고 범죄를 저지하는 노력을 계속한다.','/qb71Ji4zPhgkFX8KgozzIfdE00g.jpg',to_date('05/09/22','RR/MM/DD'),8,2913,'크리미널 마인드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (44217,'Vikings','CA','[10759-18-10768]','en','2013년 3월 History에서 방영을 시작한 역사물. 바이킹 영웅 라그나 로스브로크는 새로운 대륙을 향해 탐험하고 싶어하지만 카테가트의 영주인 백작은 모험적인 항해를 원치 않아 라그나의 의견을 묵살한다. 라그나는 친구이자 배를 만드는 기술자인 플로키의 도움을 받아 백작 몰래 출항에 성공한다. 라그나는 새로운 대륙인 잉글랜드를 발견하고 동료들과 함께 노섬브리아 왕국 영토에 있는 수도원을 잔인하게 약탈하고 수도승 애설스탠을 노예로 삼는다. 처음 보는 바이킹의 야만적인 침략에 노섬브리아 왕국은 크게 분노하면서도 바이킹을 두려워하는데...','/oktTNFM8PzdseiK1X0E0XhB6LvP.jpg',to_date('13/03/03','RR/MM/DD'),8,5440,'바이킹스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (31910,'ナルト 疾風伝','JP','[16-10759-10765]','ja','<주간 소년 점프>에 연재되면서 폭발적인 인기를 모았던 ''나루토''를 애니메이션으로 만들었다. 한국에서도 단행본이 나와 많은 인기를 얻고 있다. 나루토와 동료들이 닌자가 되기 위한 모험을 떠나는 흥미진진한 작품. 

닌자 마을 중 하나인 나뭇잎 마을. 매일같이 장난만 치며 공부도 뒤쳐져서 졸업조차 불안하기만 한 문제아 나루토. 그런 그이지만 마을에서 제일 가는 닌자, ''호카게''가 되고 싶다는 커다란 꿈을 지니고 있다. 하지만, 자신의 출생의 비밀을 안 나루토는 결의를 새롭게 다지고 같은 학교 학생인 사스케, 사쿠라와 함께 닌자로서의 첫 발을 내딛게 된다.','/qOxedwaJzdms2alAmIEHEnDeDzg.jpg',to_date('07/02/15','RR/MM/DD'),8,6838,'나루토 질풍전');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (95479,'呪術廻戦','JP','[16-10759-10765]','ja','소년은 싸운다 ''올바른 죽음''을 위해  쓰라린 고통, 후회, 치욕

인간으로부터 흘러나온 부정적인 감정이 저주로 변해 일상에 숨어든다.

저주는 세상에 만연한 재앙의 근원이며, 최악의 경우 인간을 죽음으로 이끈다.

그리고 저주는 저주로밖에 없앨 수 없다.  경이적인 신체능력을 가진 소년 이타도리 유지는 아주 평범한 고등학생이었지만,

어느 날 ''저주''에 습격당한 친구를 구하기 위해 특급 주물 ''양면 스쿠나의 손가락''을 먹고 영혼에 저주가 깃들게 된다.

저주인 ''양면 스쿠나''와 몸을 공유하게 된 이타도리는 최강의 주술사인 고죠 사토루의 안내로

저주에 대항하는 전문 기관인 ''도쿄 도립 주술 고등전문학교''에 편입하게 되는데......

저주를 없애기 위해 저주가 된 소년의 돌이킬 수 없는 장렬한 이야기가 움직이기 시작한다....','/pnn223i9v5kfYku6TbqdSbPePJp.jpg',to_date('20/10/03','RR/MM/DD'),8,2193,'주술회전');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2527,'Emmerdale','GB','[10766-18]','en',null,'/ualtuRRNYa9Fj61wSuBVcuvaVDP.jpg',to_date('72/10/16','RR/MM/DD'),3,69,'에머데일');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (84958,'Loki','US','[18-10765]','en','2021년 6월 Disney+에서 방영을 시작한 드라마. 어벤져스: 엔드게임의 2012년 뉴욕 전투 직후. 아스가르드로 연행되던 로키는 뜬금없이 자신 앞에 밀려온 테서랙트를 들고 탈출해 또다른 가능성의 로키로 분화된다. 하지만 엉겹결에 고비 사막 한 가운데에 추락한 로키는 포털을 열고 나타난 TVA 요원들에 의해 단숨에 제압당하고 연행된다. 한편 1549년 프로방스 지방에 있는 성당, 모비어스는 이곳에서 헌터들에게 시간선 간섭이 일어났다는 보고를 받는데...','/xNpqbYzKvL2hmG8L8myIkF9uLGR.jpg',to_date('21/06/09','RR/MM/DD'),8,8896,'로키');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (90462,'Chucky','US','[80-10765]','en','교외 야드 세일에서 빈티지 처키 인형이 나타난 후 살인 사건이 일어나고 그로 인해 밝혀지는 마을의 위선과 비밀을 다룬 이야기','/m9umrjNgWCxWEyNDxc0ENr24GVB.jpg',to_date('21/10/12','RR/MM/DD'),7,3140,'처키');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1655,'PBS NewsHour','US','[10763]','en',null,'/5nfFB1wHQmNxkjaMNNMendPIRzb.jpg',to_date('75/10/20','RR/MM/DD'),5,32,'PBS NewsHour');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (121726,'Love Island España','ES','[10764]','es',null,'/t8HcfOCBgOONjfuHAIzuJglnAZS.jpg',to_date('21/04/11','RR/MM/DD'),0,0,'Love Island España');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (74428,'Rosario Tijeras','MX','[18]','es',null,'/q03eQL8AUx49lVH6IT3IlmWzhQu.jpg',to_date('16/10/30','RR/MM/DD'),7,1290,'Rosario Tijeras');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (115036,'The Book of Boba Fett','US','[10759-10765]','en','2021년 12월 Disney+에서 방영을 시작한 SF물. 전설적인 현상금 사냥꾼 보바 펫과 용병 페넥 쉔드가 행성 타투인의 모래땅에 대한 권리를 주장하기 위해 우주를 항해하는 이야기.','/A5EAZoRPv7ia3sqRkcW5XogCDGF.jpg',to_date('21/12/29','RR/MM/DD'),8,1526,'북 오브 보바 펫');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (4614,'NCIS','US','[80-10759-18]','en','NCIS는 미국의 수사드라마 시리즈로 미해군과 해병대 관련 범죄수사를 담당하는 가상의 해군범죄수사대에 관한 드라마.','/lSTchtc26YNdOjdKvZtLs22SokL.jpg',to_date('03/09/23','RR/MM/DD'),7,1792,'NCIS');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60625,'Rick and Morty','US','[16-35-10765-10759]','en','술에 절어 사는 천재 과학자 릭은 투정이 심한 10대 손자 모티를 데리고 외계와 대체 현실로 아슬아슬한 모험을 떠난다.','/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',to_date('13/12/02','RR/MM/DD'),8,6447,'릭 앤 모티');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (73586,'Yellowstone','US','[37-18]','en','미국 최초의 국립 공원과 국경을 접하는 사람들의 지속적인 공격을 받으면서 미국에서 가장 큰 목장을 관리하는 존 던트의 이야기','/43nVQqVsrshaOx9GfJq6JstsfCX.jpg',to_date('18/06/20','RR/MM/DD'),8,1012,'옐로우스톤');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (157936,'Por Ti','PT','[]','pt',null,'/7GmlOYoR2GNiBRFs47azHIcqncR.jpg',to_date('22/03/07','RR/MM/DD'),4,6,'Por Ti');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (39677,'Supervivientes','ES','[10764]','es',null,'/blsLWWZW5YRSeRLzvkS1vLi5YCF.jpg',to_date('06/05/02','RR/MM/DD'),1,4,'Supervivientes');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (76231,'Mayans M.C.','US','[80-18]','en','`마얀스 M.C.''는 ''선스 오브 아나키'' 시리즈의 다음 장이다. 잭스 텔러 이후의 세계를 배경으로, 이지키얼 ‘이지’ 레예스는 막 감옥에서 출소했고, 캘리포니아와 멕시코 사이 국경 마얀스 MC 지부의 유망주다. 자부심 넘치는 라틴 가족의 재능 있는 아들이자, 한때 총아였던 이지의 아메리칸 드림을 향한 여정은 국경 지역의 폭력 사태로 소멸되고 만다. 작은 마을에서 새로운 정체성을 만들어가야 하는 이지의 복수에 대한 열망은, 결코 원하지 않았고 또 절대 탈출할 수 없는 삶으로 그를 인도한다.','/pneaBHGQ5BqGJ3afxlPezL5czZB.jpg',to_date('18/09/04','RR/MM/DD'),8,448,'마얀스 M.C.');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (79699,'La hija del Mariachi','CO','[10766-18]','es',null,'/52jdBKWqtgl9qj6SFf7Z2H0qqvN.jpg',to_date('18/05/20','RR/MM/DD'),8,1207,'La hija del Mariachi');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (291,'Coronation Street','GB','[10766]','en',null,'/xe6y8SJU0NyGEECu2LV9cXoY81g.jpg',to_date('60/12/09','RR/MM/DD'),5,70,'코로네이션 스트리트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (128794,'La Desalmada','MX','[10766-18]','es',null,'/mOXCTdOjHEjynwbWXgOmLw48sjq.jpg',to_date('21/07/05','RR/MM/DD'),4,3,'La Desalmada');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (128510,'真・一騎当千','JP','[16-35-10759-18-10765]','ja',null,'/xDcjHWwtKrus96DYggZSANq14Vn.jpg',to_date('22/05/17','RR/MM/DD'),3,2,'진 일기당천');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (128839,'La Brea','US','[18-10765-10759]','en','거대한 싱크홀이 로스엔젤레스 한복판에서 생기면서 수백 명의 사람들과 건물들이 깊은 곳으로 빠져든다.  싱크홀에 빠진 사람들은 신비롭고 위험한 원시시대에 있다는것을 알게 되고 살아남기 위해 서로 뭉친다.  한편, 세계의 다른 국가들은 무슨 일이 일어났는지 이해하려고 필사적으로 노력한다.  이번 재난으로 분열된 한 가족은 서로에게 돌아가는 길을 찾기 위해 설명할 수 없는 이 사건의 비밀을 풀어야 한다.','/6tAzoo2e9GpJt4tfiRkNHx97e36.jpg',to_date('21/09/28','RR/MM/DD'),7,709,'라 브레아');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (59941,'The Tonight Show Starring Jimmy Fallon','US','[35-10767]','en',null,'/if7ECoH4xaYw5S8gomNIEmtwTxP.jpg',to_date('14/02/17','RR/MM/DD'),6,178,'The Tonight Show Starring Jimmy Fallon');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (152483,'The Boys Presents: Diabolical','US','[16-10759]','en','''디아볼리컬''과 함께 이전에 보지 못했던 ''더 보이즈'' 세계관에 깊이 빠져본다. 어째서인지 아직도 업계에 남아 있는, 기묘하고 뒤틀리고 광적인 연예인들이 새롭게 창작한 8부작 애니메이션 앤솔러지 시리즈.','/kZKfZWwFOAicgoKS2IO7oM1GuHZ.jpg',to_date('22/03/03','RR/MM/DD'),7,70,'더 보이즈: 디아볼리컬');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (197248,'Conversations with a Killer: The John Wayne Gacy Tapes','US','[99]','en','그는 유력 인사들과 만찬을 즐겼다. 동시에 취약한 이들을 먹잇감 삼았다. 미소 짓는 얼굴 뒤에 소름 끼치는 어둠을 감추고 있었던 가학적인 연쇄 살인마의 초상.','/sd96o6FjufksMHlVqhUjHX9JxSb.jpg',to_date('22/04/20','RR/MM/DD'),7,26,'살인을 말하다: 존 웨인 게이시 테이프');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (4604,'Smallville','US','[10765-10759-18]','en','우리에게 슈퍼맨으로 친숙한 클라크 켄트의 유년기를 새로이 재조명한 워너 브라더스사의 SF시리즈물 드라마','/dc9a9n4g9Ibs485t5eBtyNG0mcr.jpg',to_date('01/10/16','RR/MM/DD'),8,3152,'스몰빌');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1413,'American Horror Story','US','[18-9648-10765]','en','''공포''라는 주제로 시즌마다 다른 이야기를 풀어가는 앤솔로지 시리즈. 인간이 가지고 있는 사악한 근성을 탐구하는 동시에 인간이 느끼는 초자연적 두려움과 일상 속의 공포를 조명한다.','/mckCh2GYSerIqyCyPSLIStLvmZF.jpg',to_date('11/10/05','RR/MM/DD'),8,4444,'아메리칸 호러 스토리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (14424,'Malhação','BR','[10766]','pt',null,'/hTDsUXq3jHWdTBlKpnjb6XLADfm.jpg',to_date('95/04/24','RR/MM/DD'),4,13,'Malhação');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (12965,'María la del Barrio','MX','[18-10766]','es',null,'/17iXdZ7muzMefCtPz0LuFnjQqcC.jpg',to_date('95/08/14','RR/MM/DD'),7,473,'María la del Barrio');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (106651,'지옥','KR','[18-80-9648-10765]','ko','어느 날 기이한 존재로부터 지옥행을 선고받은 사람들. 지옥으로부터의 고지를 받은 자는 어김 없이 예정된 시간에 지옥의 사자들에게 끌려가는 일이 서울 한복판에서 모두가 지켜보는 가운데 일어난다. 충격과 두려움에 휩싸인 도시에 대혼란의 시대가 도래한 가운데, 신흥 종교 단체 새진리회의 의장 정진수는 이것이 진정으로 현실 세계에서 일어나고 있는 신의 집행임을 사람들에게 설파한다. 한편 일부는 새진리회에 맞서 싸우며 사건의 실체를 밝히려 한다.','/sgTu75c5PJsRHDMSna0ha8bhYWn.jpg',to_date('21/11/19','RR/MM/DD'),7,599,'지옥');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (56295,'Halo 4: Forward Unto Dawn','US','[10765-10759]','en','서기 2525년,  우주 식민지화로 반란군과 끊임없는 전쟁을 벌이는 인류  식민지 중 하나인 서시너스-4 행성의 코불로 사관학교에서는 반란군들을 일망타진하기 위한 정예부대가 혹독한 훈련을 소화해내고 있다. 그러던 어느 날, 인간 말살을 도모하는 외계 생명체 코버넌트가 갑작스럽게 침공하고 행성은 순식간에 전멸 위기에 처하고 만다.  죽음이 코 앞에 다가왔다고 생각한 순간 극적으로 마스터 치프가 등장해 살아남은 생도들을 구해낸다. 행성을 탈출하기 위해 이동하던 중 이들은 절체절명의 위기에 빠지고, 마스터 치프와 생존자들은 함께 외계 생명체에 맞서 자신의 한계에 도전하는 최후의 작전을 펼치게 되는데…','/7CYryCtfJBiIAu4F2FIusg6BP5Z.jpg',to_date('12/10/05','RR/MM/DD'),6,582,'헤일로: 슈퍼 솔저');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (40075,'Gravity Falls','US','[16-35-9648-10765-10762]','en','2012년 여름, 디퍼와 메이블의 부모님은 여름방학동안 쌍둥이 남매를 오리건 주의 ''그래비티 폴즈''라는 시골의 삼촌 할아버지 댁으로 보낸다. 그곳에서 남매는 그들의 삼촌 할아버지인 스탠의 집 겸 관광지인 수수께끼 가게의 다락방에서 여름을 보내게 된다.

스탠과 달리 평소 그래비티 폴즈에 대해 이상하게 생각했던 디퍼는 숲에서 표지에 황금색 육손 모양에 ''3''이라고 적혀진 책을 발견하였는데, 거기엔 그래비티 폴즈의 온갖 미스터리에 대해 적혀 있었다. 남매는 새로 사귄 친구들과 그래비티 폴즈에서 괴상한 일을 겪으면서 의문점을 하나하나 풀어가게 되는 이야기이다.','/wgBaQQtfwGFGQcmTKiGmZGdzSTg.jpg',to_date('12/06/15','RR/MM/DD'),8,2010,'괴짜가족 괴담일기');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (7458,'El Cartel de los Sapos','CO','[10759-18]','es',null,'/cSvzG2B2uafu5BoP5nt0OvrVrQG.jpg',to_date('08/06/04','RR/MM/DD'),7,486,'El Cartel de los Sapos');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (116799,'The Lincoln Lawyer','US','[18-80]','en','인습은 버리고 이상을 따른다. 도시의 크고 작은 사건들을 다루는 변호사. 그의 사무실은 다름 아닌 링컨 타운카 뒷좌석이다. 마이클 코널리의 베스트셀러 소설을 바탕으로 하는 시리즈.

로스앤젤레스의 잘나가는 변호사, 미키 홀러. 사고를 당한 후 자취를 감췄던 그가 한 살인 사건을 맡으면서 변호사로 복귀한다. 자신의 분신과도 같은 링컨 차를 타고서.','/4jSaIqEU8CPBBNn4iVCK6wzPjSx.jpg',to_date('22/05/13','RR/MM/DD'),8,49,'링컨 차를 타는 변호사');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (93449,'Tamron Hall','Unknown','[10767]','en',null,'/mK2vLB0iIUAk98wEufBJfWMiTPi.jpg',to_date('19/09/09','RR/MM/DD'),5,9,'Tamron Hall');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (112888,'여신강림','KR','[35-18]','ko','외모 콤플렉스를 가지고 있다가 화장을 통해 여신이 된 주경과 남모를 상처를 간직한 수호가 만나 서로의 비밀을 공유하며 성장하는 자존감 회복 로맨틱 코미디','/gaCOvKGG2qEnsijNHEAigYcQ1U3.jpg',to_date('20/12/09','RR/MM/DD'),8,942,'여신강림');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (62914,'Merlí','ES','[35-18]','ca',null,'/eBzpj7PxyeRFCIYHQjB5kDnhX4a.jpg',to_date('15/09/14','RR/MM/DD'),8,852,'Merlí');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (85937,'鬼滅の刃','JP','[16-10765-10759]','ja','2019년 4월 Tokyo MX에서 방영을 시작한 애니메이션. 고토게 코요하루의 동명의 만화를 원작으로 한다. 다이쇼 시대, 가난하지만 가족들과 함께 행복한 일상을 보내던 카마도 탄지로. 설이 오기 전에 숯을 잔뜩 팔아 가족들을 배불리 먹여주고 싶었던 탄지로는 혼자 마을로 내려가 숯을 판다. 다음날이 밝고 집에 도착한 탄지로는 가족들이 처참하게 몰살당한 모습을 보고, 유일하게 살아있던 여동생 네즈코를 구하기 위해 그녀를 의사에게 데려가려 하지만 네즈코는 이미 혈귀가 되어 있었다. 가혹한 운명의 사슬을 끊어내고 세상에서 혈귀를 멸하려, 지금 탄지로가 복수의 칼날을 높이 든다.','/iR6T6QxSJpSQi1S4GGjGWLQkSva.jpg',to_date('19/04/06','RR/MM/DD'),8,3978,'귀멸의 칼날');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (122587,'カッコウの許嫁','JP','[16-35]','ja','아기 때 뒤바뀌어, 드디어 진짜 부모님과 만나게 된 고교생 ‘우미노 나기’.

그날, 영애들이 다니는 명문 학교의 여고생 ‘아마노 에리카’를 우연히 만나, 누군지도 모르는 약혼자와의 결혼을 막고 싶은 그녀의 부탁에 반 강제로 남자친구 역할을 맡게 된다.

하지만, 이 두 사람이야 말로 뒤바뀐 아이이자, 약혼자였다!

알고 보니 두 자녀를 사랑하는 부모들에 의해 ‘나기’와 ‘에리카’는 양가가 인정한 약혼 관계가 되어 동거 생활을 하기로 정해졌던 것!

그러나 같은 반의 ‘세가와 히로’를 사랑하는 ‘나기’와 아버지에게 반발하는 ‘에리카’가 합의를 본 것은, "서로 일절 관여하지 말 것".

뒤죽박죽, 우당탕거리는 인생교착 러브 코미디 스타트!','/ub9CwVbGexT75YCrdwgka9AljD2.jpg',to_date('22/04/24','RR/MM/DD'),6,4,'뻐꾸기 커플');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1981,'Charmed','US','[35-18-9648-10765]','en',null,'/z4bPJ1BWU2EtV69NII2GVvsugQ2.jpg',to_date('98/10/07','RR/MM/DD'),8,1749,'참드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (88055,'Servant','US','[18]','en','슬픔에 빠진 한 필라델피아 부부의 이야기를 다루는 드라마. 입에 담지 못할 비극으로 인해 이들의 결혼 생활에 균열이 생기고, 불가사의한 힘이 집 안으로 들어오도록 문을 열게 된다. M. 나이트 샤말란 제작 참여.','/7PtbLIhpRGpJYmvs3VNeJLRpwYQ.jpg',to_date('19/11/28','RR/MM/DD'),7,475,'서번트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (33238,'런닝맨','KR','[35-10764]','ko','대한민국 최고의 연예인들이 곳곳에 있는 미션을 해결하고, 끊임없는 질주와 긴박감 넘치는 대결을 통해 대한민국 랜드마크들의 숨겨진 뒷모습을 전격 공개하는 프로그램','/15SMnscZqd7HZ0bzruatOcKUlOV.jpg',to_date('10/07/11','RR/MM/DD'),8,133,'런닝맨');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (63764,'Señora Acero','US','[18-80-10766]','es',null,'/vXhBxsvpW2mGuXRbIK5Yazdp8Zg.jpg',to_date('14/09/23','RR/MM/DD'),7,405,'Señora Acero');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2004,'Malcolm in the Middle','US','[10751-35-18]','en',null,'/uwslHj6nEyPX5IbNXhuEeI0PTth.jpg',to_date('00/01/09','RR/MM/DD'),8,3081,'말콤네 좀 말려줘');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (124363,'魔法使い黎明期','JP','[16-35-10759-10765]','ja','"나는 기억을 하지 못한다. 나는 대체 무엇인지."

마법 학교 학생 세빌은 입학하기 전의 기억이 없었다.

자신이 왜 여기 있는지도 모르는 채 보내는 학교생활은 어딘가 모르게 공허해서,

노력하는 방법도 알지 못한 채 성적은 항상 최하위였다.

그런 세빌에게 마법 학교의 학장인 알바스가 갑자기 위험한 특별 실습 이야기를 꺼냈다.

"마녀사냥이 아직 시행되고 있는 지역에서, 마법의 유용성을 널리 알렸으면 해."

마녀와 교회의 전쟁이 종결된 후 수년.

세계는 아직 마녀와 마법을 완전히 받아들이지는 못했다.

때는 마법사의 여명기.

이것은, 그 무엇도 아닌 소년이 마음속에 상처를 간직한 동료들과 자신을 되찾는 이야기.','/2CyNqxF0XPcL4kHdWvCVHBhFgnm.jpg',to_date('22/04/08','RR/MM/DD'),6,6,'마법사의 여명기');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (33987,'Corazon Valiente','US','[10766-18-10759]','es',null,'/4YWuiRyqnfalauuFC06S5yw92gH.jpg',to_date('12/03/06','RR/MM/DD'),7,280,'Corazon Valiente');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (93741,'Jurassic World: Camp Cretaceous','US','[16-10762-10759]','en','세계 최초로 끝내주게 멋진 경험을 하게 될 줄 알았다. 백악기 캠프 1기 참가자로 뽑힌 여섯 명의 십 대. 이들은 곧 공포에 휩싸인다. 최고의 포식자 공룡이 풀려났다!','/nkCbCmlwjwT6QL44DqG7qE9ch8H.jpg',to_date('20/09/18','RR/MM/DD'),8,1584,'쥬라기 월드: 백악기 어드벤처');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (83215,'Casados à Primeira Vista','PT','[10764]','pt',null,'/j5unA87lac80OJtnkcEKxwgodHT.jpg',to_date('18/10/21','RR/MM/DD'),3,2,'Casados à Primeira Vista');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (549,'Law & Order','US','[80-18]','en','추악한 성범죄자를 쫓아 사건을 해결하는 특별수사단의 통쾌한 활약을 그린 수사시리즈','/1J8QWZM7DQxJ2b7vYK3munMK5rh.jpg',to_date('90/09/13','RR/MM/DD'),7,359,'로 앤 오더');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (105009,'東京リベンジャーズ','JP','[18-16-10759-80]','ja','전 여자 친구의 죽음을 계기로 12년 전 중학교 시절로 타임슬립 하면서 벌어지는 이야기','/fMSqUzQ0wq3lFSy4WRhOusAjBrY.jpg',to_date('21/04/11','RR/MM/DD'),8,830,'도쿄 리벤저스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (95557,'Invincible','US','[16-10765-10759-18]','en','마크 그레이슨은 17살에 슈퍼파워를 물려받자 아버지와 함께 지구에서 가장 위대한 영웅 중 하나가 된다. 드디어 꿈이 이루어졌지만 충격적인 사건이 모든 것을 뒤흔든다.','/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',to_date('21/03/25','RR/MM/DD'),8,2992,'인빈시블');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (4607,'Lost','US','[10759-9648]','en','2004년 9월 ABC에서 방영을 시작한 미스테리 스릴러. 남태평양의 한 섬에 오세아닉 815 항공기가 불시착하지만 동체 부분과 후미 부분이 부서지며 공중분해되면서 이름모를 섬에 떨어진다. 의사, 이송 중이던 죄수, 전직 이라크군, 로큰롤 가수 등 다양한 직업을 가진 그들은 구조되어 살아남기 위해 여러 방법을 동원한다. 하지만 구조대는 오지 않고, 밤이 되자 정글 안에서는 무시무시한 소리가 들려온다. 서서히 다가오는, 그러나 보이지 않는 정체 불명의 괴물과 괴이현상들. 고립된 생존자들은 점점 두려움에 빠져들고 극한의 상황으로 내몰리게 된다.','/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg',to_date('04/09/22','RR/MM/DD'),7,2813,'로스트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (19530,'霹雳布袋戏','TW','[10759-18]','zh',null,'/c6CKmPSXO8omy0eHQX7TcEtz72i.jpg',to_date('88/06/01','RR/MM/DD'),10,3,'霹雳布袋戏');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (127235,'Invasion','US','[10765-18]','en','갑작스런 외계인의 침공으로 생존을 위협받는 인류. 일상은 사라졌고 세상은 혼란에 빠졌다. 각자가 처한 믿을 수 없는 현실을 극복하려는 다섯 명의 평범한 사람들. 시시각각 발생하는 위기 상황에 대처할 수 있을까?','/7rpiHZx10Nm50AtzTUEO9eyaKdq.jpg',to_date('21/10/21','RR/MM/DD'),7,616,'인베이션');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (114868,'終末のワルキューレ','JP','[16-10759-10765]','ja','7백만 년 인류 역사에 종지부를 찍기로 한 신들. 그들이 인간에게 마지막 기회를 준다. 전 세계의 신과 사상 최강의 인간이 일대일로 맞붙는 열세 번의 승부, ‘라그나로크’가 지금 시작된다.','/ygE1AEV6pXFuCzbjS9ts59LxDm5.jpg',to_date('21/06/17','RR/MM/DD'),8,1049,'종말의 발키리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (17572,'Kick Buttowski: Suburban Daredevil','US','[10762-10759-16-35]','en',null,'/syxcG3suyf3U00z5HOuLbZ9eozl.jpg',to_date('10/02/13','RR/MM/DD'),8,518,'Kick Buttowski: Suburban Daredevil');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1100,'How I Met Your Mother','US','[35]','en','《내가 그녀를 만났을 때》는 미국 CBS에서 방영되었던 시트콤이다. 소울메이트를 찾기 위한 테드의 기나긴 여정. 어른이 된 테드가 아이들에게 아빠와 엄마가 만난 이야기를 들려주며 회상하는 장면들로 이뤄진다.','/dvxSvr6OmYGvvt8Z1VdBlPfL1Lf.jpg',to_date('05/09/19','RR/MM/DD'),8,3386,'내가 그녀를 만났을 때');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (42705,'はじめの一歩','JP','[16-35-18-10759]','ja','어려서 아버지를 여의고 어머니와 단 둘이 낚시 가게를 꾸려나가던 왕따 고교생 마쿠노우치 잇포는 같은 학교의 불량학생 우메자와 일행에게 괴롭힘을 당하던 중 로드워크 중인 카모가와 짐 소속의 간판 복서 타카무라 마모루의 도움을 받게되고 복싱을 동경, 강해지기 위해 복싱을 시작한다. 같은 나이의 복서 미야타 이치로와 선의의 라이벌이 되어 프로 복서가 되고, 경기를 치루면서 점점 진정한 강함이 무엇인지를 깨닫기 시작하는데...','/a5g4AltmlNq0e1hN1jugemNa5wX.jpg',to_date('00/10/03','RR/MM/DD'),8,663,'더 파이팅');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (15260,'Adventure Time','US','[16-35-10765]','en','이 작품은 종말 이후의 세상인 우 랜드에서 살고 있는 인간 소년 핀과, 마법의 힘으로 몸의 크기와 모양을 자유자재로 변화할 수 있는 강아지 제이크의 모험을 다루고 있다. 워드는 핀을 ‘높은 도덕성을 가진 용맹한 어린 아이’라고 표현했고, 제이크는 영화 《미트볼》에서 빌 머리가 맡은 역할인 트리퍼 해리슨(Tripper Harrison)에서 영감을 받았다고 했다. 그 외 등장인물로는 캔디 왕국의 통치자인 버블검 공주, 악당이자 어딘가 이상한 얼음대왕, 록 음악을 좋아하는 뱀파이어 여왕 마르셀린 등이 있다.','/rk9hP9oWxdz70HjH2khCl3wSYu8.jpg',to_date('10/04/05','RR/MM/DD'),8,2034,'핀과 제이크의 어드벤처 타임');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (119243,'iCarly','US','[35]','en',null,'/anOybngCmtscpYUYmbghHHnSi0R.jpg',to_date('21/06/17','RR/MM/DD'),7,642,'아이칼리');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (17610,'NCIS: Los Angeles','US','[10759-18-80-9648]','en','LA 지역에서 활동하는 NCIS 특수작전부 소속 위장잡입수사 전문요원들의 활약을 그린다. NCIS의 첫번째 스핀오프 시리즈.','/TIIgcznwNfNr3KOZvxn26eKV99.jpg',to_date('09/09/22','RR/MM/DD'),7,906,'NCIS: 로스앤젤레스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (30984,'ブリーチ','JP','[10759-16-10765]','ja','''쿠로사키 이치고''는 유령을 볼 수 있는 15세의 남자다. 특수한 체질을 가지고도 평범한 생활을 하던 이치고에게 갑자기 스스로를 사신이라고 소개하는 소녀 ''쿠치키 루키아''가 나타난다. 유아울러 산 사람, 죽은 사람 안 가리고 공격해서 영혼을 먹어치우는 나쁜 혼령 ''호로''도 모습을 드러낸다. 그런데 호로로 인해 이치고의 가족이 쓰러져가는데...','/ekp9PbSODHiTXXqnHJ4Sq6YHkhq.jpg',to_date('04/10/05','RR/MM/DD'),8,1174,'블리치');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (65555,'Kara Sevda','TR','[18]','tr',null,'/xnhSuHVbp4KSoehKLX32QJeQ5CO.jpg',to_date('15/10/14','RR/MM/DD'),7,580,'Kara Sevda');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (79744,'The Rookie','US','[80-18]','en','이혼 후 은행 강도를 당한 일을 계기로 LAPD에 지원한 40세의 최고령 신입을 중심으로 펼쳐지는 이야기','/iCf0II8ueZa47fiaVhdgmGdvaCC.jpg',to_date('18/10/16','RR/MM/DD'),8,958,'더 루키');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (14750,'Na Wspólnej','PL','[10766]','pl',null,'/uksRhdaOn64bO5d33d7rcTbrhJI.jpg',to_date('03/01/27','RR/MM/DD'),3,3,'Na Wspólnej');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (107365,'Bel-Air','US','[18]','en','웨스트 필라델피아의 고등학생이자 농구 유망주인 윌 스미스. 어느 날 지역 갱단과의 다툼에 휘말려 경찰에 체포됐다가 뜻밖의 도움으로 풀려나지만 아들의 안위를 염려한 엄마에게 떠밀려 하루아침에 LA 벨에어라는 부촌의 이모 집에서 생활하게 된다. 어린 시절, 아버지가 말도 없이 떠나는 바람에 엄마 아래에서 자란 윌은 특유의 밝은 성격과 뛰어난 농구 실력으로 주위에서 인기를 독차지하며 자랐지만 아버지의 부재에 대해선 늘 마음 한구석에 공허함이 자리하고 있다.','/mYxOyby7cqzEAR1XQ22yXkcdKbx.jpg',to_date('22/02/13','RR/MM/DD'),7,72,'벨 에어');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (46298,'ハンターｘハンター','JP','[10759-16-18]','ja','주인공 곤 프릭스는 아버지 진 프릭스를 찾기 위해 헌터 시험에 응시한다. 그리고 그곳에서 새로운 친구들과 만나 모험을 떠난다.','/A41SbgyfGuehD9TRBrQFNXgsLmX.jpg',to_date('11/10/02','RR/MM/DD'),8,1111,'헌터×헌터');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (502,'Sesame Street','US','[10762-35]','en','새서미 스트리트는 미국 어린 아이들을 위한 장수 TV 시리즈였습니다. 이 프로그램은 교육적인 목적으로 만들어졌지만 짐 핸슨의 인형극, 애니메이션, 짧은 영화, 유머와 문화에 대한 내용들로 매우 창의적인 내용들을 다루고 있습니다. 첫 시리즈는 1969년 11월 10일 방영되었으며 당시 긍정적인 리뷰가 있었고 논란이 되기도 하였고 높은 평가를 받았습니다.','/s0LGjlRqbMPUiolvM9hXPgYgILn.jpg',to_date('69/11/10','RR/MM/DD'),7,177,'새서미 스트리트');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (158396,'Krakowskie potwory','PL','[10765]','pl','과거의 망령에 시달리는 젊은 여성. 우연한 계기로 미스터리한 교수와 그가 이끄는 학생 그룹에 합류한다. 특별한 재능을 지닌 그 학생들은 초자연적 현상을 조사하고 악마와 싸운다는데.','/fLvWYA6fbNNvPyswLZxHnyF6VtU.jpg',to_date('22/03/18','RR/MM/DD'),6,30,'크라쿠프의 괴물들');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2288,'Prison Break','US','[10759-80-18]','en','2005년 8월 FOX에서 방영을 시작한 스릴러. 로욜라 대학에서 건축학을 전공한 후 미들턴 재판소 건축 설계 엔지니어로 근무하던 마이클 스코필드(웬트워스 밀러)는 그의 형인 링컨(도미닉 퍼셀)이 부통령 동생의 살인 누명을 쓰고 수감되어 사형을 선고받자, 형을 탈옥시키고 누명을 벗기기 위해 몸 전체에 교도소의 지도를 문신으로 세기고 의도적으로 은행강도를 저질러 형이 있는 감옥에 수감된다. 하지만 그가 들어가기 전에 세워둔 완벽하다고 생각했던 계획들은 인간이라는 장애물 앞에 조금씩 어긋나기 시작한다.','/5E1BhkCgjLBlqx557Z5yzcN0i88.jpg',to_date('05/08/29','RR/MM/DD'),8,3686,'프리즌 브레이크');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (196614,'Hasta que la plata nos separe','CO','[10766-18]','es',null,'/wWlPY4zmuJDelcOwb4ph9lGo5Ew.jpg',to_date('22/05/10','RR/MM/DD'),7,11,'Hasta que la plata nos separe');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (7821,'El Chavo Animado','MX','[35]','es',null,'/fIQpvawxgajLhjZfN7XS0stzesJ.jpg',to_date('06/10/21','RR/MM/DD'),7,357,'El Chavo Animado');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (16395,'MasterChef Australia','AU','[10764]','en',null,'/m5akdtbWznF8KpOewKyKw0C36s1.jpg',to_date('09/04/27','RR/MM/DD'),7,57,'MasterChef Australia');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1400,'Seinfeld','US','[35]','en','코미디언 제리 사인필드가 직접 자신의 삶을 무대로 연기한 드라마','/u3mFyqIprL5ou8Ue04Ecac6iDi7.jpg',to_date('89/07/05','RR/MM/DD'),8,1333,'사인필드');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (81772,'Oteckovia','SK','[10751-35]','sk',null,'/r1hDy1wJ52NEilfcSzs0ocHEJZl.jpg',to_date('18/01/01','RR/MM/DD'),7,6,'Oteckovia');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (139512,'乙女ゲー世界はモブに厳しい世界です','JP','[16-35]','ja','검과 마법의 ‘여성향게임‘ 세계에 전생한 평범한 사회인이었던 ‘리온’.

이곳은 여존남비의 세계였고, 예외는 게임에서 공략 대상이었던 왕태자가 이끄는 미남군단 정도였다. 그러나, 괴롭힘에 절망한 ‘리온’에게는 어떤 한 가지 무기가 있었다.

그것은 전생에서 시건방진 여동생이 억지로 시켰던 이 게임에 관한 “지식”이었다. 모브로써 시골 에서 한가롭게 보내는 것으로 목표로 하고 있던 ‘리온’이었지만, 게임의 지식을 사용해 마음대로 하고 싶은 여자들과 미남들에게 뜻하지않게 반기를 들고 마는데...','/AaQek8x8ZpL9RFoler6qZunh2Ix.jpg',to_date('22/04/03','RR/MM/DD'),6,5,'여성향 게임 세계는 모브에게 가혹한 세계입니다');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (11890,'Goede Tijden, Slechte Tijden','NL','[10766]','nl',null,'/5Nken8tk94us0BVQlFyioGQQUxF.jpg',to_date('90/10/01','RR/MM/DD'),4,8,'Goede Tijden, Slechte Tijden');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (2691,'Two and a Half Men','US','[35-18]','en','자유로운 영혼이었던 찰리가 떠나간 이후, 앨런과 그의 아들 제이크에게 찾아온 앨런의 친구 월든이 다시금 새로운 가족으로 생활하게 되면서 벌어지는 코믹한 일상을 담은 시트콤','/A9QDK4OWpv41W27kCv0LXe30k9S.jpg',to_date('03/09/22','RR/MM/DD'),7,2271,'두 남자와 1/2');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (56425,'グラップラー刃牙','JP','[16-10759-18]','ja','격투왕 바키','/9LqCt1xQb6yMyfxzBNKZGPZ4q9e.jpg',to_date('01/01/08','RR/MM/DD'),7,231,'격투왕 바키');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (105214,'Oscuro deseo','MX','[9648-18]','es','교수로, 판사의 아내로, 완벽한 삶을 꾸려온 여인. 어느 주말, 그녀의 일상이 흔들리기 시작한다. 하룻밤의 일탈로 끝날 줄 알았던 부정, 그리고 갑작스러운 의문의 죽음. 보이지 않는 수면 아래, 그곳엔 어떤 진실이 감춰져 있나.','/2sxCw7lxapStXc2phzcJCR6LGRL.jpg',to_date('20/07/15','RR/MM/DD'),7,4066,'검은 욕망');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (13945,'Gute Zeiten, schlechte Zeiten','DE','[18-10766]','de',null,'/fNHBzjxsydcAssxXqb5IV2obDdU.jpg',to_date('92/05/11','RR/MM/DD'),6,6,'Gute Zeiten, schlechte Zeiten');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (70523,'Dark','DE','[10765-18-9648-80]','de','어느 날, 아이가 사라졌다. 처음이 아니다. 3대를 이어온 미스터리, 절박하게 답을 찾으려는 네 가족. 현재와 과거가 얽힌 혼돈의 근원에는 무엇이 도사리고 있는 걸까.','/4e8FR7ORN7XtJm5TsGKGtyTQah6.jpg',to_date('17/12/01','RR/MM/DD'),8,4974,'다크');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (202348,'凭栏一片风云起','CN','[18]','zh',null,'/vgMsw0SOvCLS9MlGSaHF5mgTBLh.jpg',to_date('22/05/19','RR/MM/DD'),5,2,'凭栏一片风云起');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (57243,'Doctor Who','GB','[10759-18-10765]','en','타임로드라는 종족의 외계인인 닥터가 그의 동료들과 함께 시공간을 누비는 여행을 하며 때때로 지구와 인류 그리고 우주를 구하는 이야기.','/ezk0jjMI24HoxRMSCzkc1IBRy0a.jpg',to_date('05/03/26','RR/MM/DD'),7,2344,'닥터 후');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (80986,'DC''s Stargirl','US','[10765-10759-18]','en','평범했던 10대 소녀가 마법의 지팡이를 통해 특별한 능력을 가지게 되고, 이후 스타걸이라는 슈퍼히어로가 되어 악당과 싸우는 활약상을 그린 이야기','/ogntmK9hwBomhajqYrHXUAaqkd7.jpg',to_date('20/05/18','RR/MM/DD'),7,928,'스타걸');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (123249,'その着せ替え人形は恋をする','JP','[16-35-18]','ja','히나 인형의 얼굴을 만드는 ''카시라시''를 꿈꾸는 남자 고교생 ''고죠 와카나''.

성실하고 한결 같이 히나 인형 제작에 몰두하지만 같은 세대의 유행과는 동 떨어져  좀처럼 반 친구들과 친해지지 못했다.

그런 와카나에게 있어서 언제나 반의 중심에 있고

인기가 많은 ''키타가와 마린''은 마치 다른 세계의 주민처럼 느껴졌다.

하지만 어느 날 생각지 못한 일을 계기로

마린과 비밀을 공유하게 되는데......?!

절대로 교차할 리 없던 두 사람의 세계가 움직이기 시작한다!...','/7r5Om5Ld6OzoRrXRROFiCTNpZFd.jpg',to_date('22/01/09','RR/MM/DD'),8,78,'그 비스크 돌은 사랑을 한다');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (123528,'骸骨騎士様、只今異世界へお出掛け中','JP','[16-10759-10765]','ja','눈을 떠 보니 MMORPG에서 자신이 사용하던 게임 캐릭터의 모습으로 이세계에 떨어진 ‘아크‘.

그 모습은 외형이 갑옷, 내용물은 전신골격 ''해골기사''였다.

정체를 들키면 몬스터로 몰려 토벌 대상이 될 수 있다?!

때문에 ‘아크’는 눈에 띄지 않게 용병으로 지내기로 결심하지만,

눈앞에서 일어난 악행을 내버려 둘 만한 남자는 아니었다!

해골기사님의 무자각  ''사회혁명'' 이세계 판타지!!','/o1goglhOWWCQm1WsnQmYt9XqAst.jpg',to_date('22/04/07','RR/MM/DD'),7,13,'해골기사님은 지금 이세계 모험 중');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1431,'CSI: Crime Scene Investigation','US','[80-18-9648]','en','2000년 10월 CBS에서 방영을 시작한 범죄수사물. 최첨단 장비와 과학적인 분석으로 미궁속의 사건을 해결해 가는 라스베가스 시경 과학수사과 심야근무반. 17년 경력의 베테랑 길 그리섬, 혼자서 키우는 딸과 직장 사이에 균형을 잃지 않으며 항상 최선을 다하는 캐서린 윌로스, 도박의 유혹을 뿌리치지 못하지만 날카로운 분석력을 보유한 워릭 브라운, 하바드 출신의 새라 사이들, 그리고 매력적인 남자 닉 스톡스 등 5명이 한 팀으로 구성된 이들은 사건이 미궁에 빠질 때마다 첨단 기술과 예리한 분석력으로 결정적인 단서와 증거를 확보하여 진범을 가려내기 위해 365일 24시간을 투자한다.','/9XecVOLLkbGBNnpF2PvP8vQBmww.jpg',to_date('00/10/06','RR/MM/DD'),7,859,'CSI: 라스베가스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (71789,'SEAL Team','US','[10759-18-10768]','en','국가가 요구하는 가장 위험하고 어려운 작전을 계획하고 수행하는 최정예 해군 특수부대 씰 팀의 삶을 보여주는 드라마.','/v0G8cbPtGoiTBFb4HW1hAJJFMol.jpg',to_date('17/09/27','RR/MM/DD'),8,1193,'씰 팀');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (37606,'The Amazing World of Gumball','GB','[16-10751-10765-35]','en','12살 사고뭉치 파란 고양이 검볼. 돈 버느라 언제나 바쁜 엄마. 게임과 TV에 빠진 철부지 아빠. 어리지만 똑소리 나는 여동생. 늘 검볼과 함께하는 금붕어 절친. 평범한 듯 특별한 검볼 가족의 시끌벅적한 일상을 그린 애니메이션.','/VYnnyA2hyxi3VUPgCA71mMtt69.jpg',to_date('11/05/02','RR/MM/DD'),8,998,'검볼');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (46896,'The Originals','US','[10765-18-9648]','en','뱀파이어 다이어리 스핀오프 시리즈. 최초의 뱀파이어인 클라우스, 일라이자, 레베카가 주인공이다. 클라우스는 그의 후계자 마르셀이 지배하는 뉴올리언스로 돌아온다. 반면, 늑대인간인 헤일리는 클라우스의 아이를 임신한 채로 뉴올리언스에 등장하고, 클라우스는 자신의 왕국을 재건하고 후계자를 맞아들이려 한다.','/s0EDspmzDpiRCtGHQFjAfxYBeh3.jpg',to_date('13/10/03','RR/MM/DD'),8,2751,'오리지널스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (987,'General Hospital','US','[10766]','en',null,'/tYaWB1H4Isq4BoAjxFWMjhaEP9W.jpg',to_date('63/04/01','RR/MM/DD'),5,182,'General Hospital');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1620,'CSI: Miami','US','[18-9648-80]','en','플로리다 주의 마이애미 데이드 경찰청. 호레이쇼 반장과 CSI 과학 수사 대원들은 논리적인 증거 분석과 본능적인 수사로 마이애미에서 일어나는 위험한 범죄들을 해결해나간다.','/m4xM1n2aO98y8GEu9CS3w2SvGKH.jpg',to_date('02/09/23','RR/MM/DD'),7,1287,'CSI: 마이애미');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60708,'Gotham','US','[18-80-10765]','en','젊은 시절, 고든 경감은 브루스 웨인의 부모를 살해한 자를 복수하기 위해 범죄와 부패를 막는 고담 시의 젊은 형사로 활약한다.','/2knM0D9yGrnUgECWfj6OSJl4Poa.jpg',to_date('14/09/22','RR/MM/DD'),7,2762,'고담');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (136644,'왜 오수재인가','KR','[18-9648]','ko','‘살기 위해, 가장 위에서, 더 독하게’ 성공만을 좇다 속이 텅 비어버린 차가운 변호사 오수재와 그런 그녀를 지키기 위해서라면 무엇도 두렵지 않은 로스쿨 학생 공찬의 아프지만 설레는 이야기','/vvtGGm7qTLTio5uZXwLKbN1hqM6.jpg',to_date('22/06/03','RR/MM/DD'),8,6,'왜 오수재인가');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (44914,'La Patrona','US','[18-10766]','es',null,'/sY5Uf3VQmxA3MVxSgdDrHQcKwCV.jpg',to_date('13/01/08','RR/MM/DD'),7,216,'La Patrona');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (134174,'Asesino del olvido','MX','[80-18]','es',null,'/e6FiaV1YbTPhXYlPEHbCvzM4MVb.jpg',to_date('21/10/07','RR/MM/DD'),7,3,'Asesino del olvido');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1871,'EastEnders','GB','[10766-18]','en','이스트 런던의 월포드라는 가상의 자치구에 있는 앨버트 스퀘어에 사는 사람들의 삶','/z4jgyI5TpoRZiJTNchkVkMrGQyz.jpg',to_date('85/02/19','RR/MM/DD'),3,178,'이스트엔더스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (47,'El Chavo del Ocho','MX','[35-10751]','es',null,'/lQFO5cPoYfKrACayWItroAi1Wdp.jpg',to_date('73/02/26','RR/MM/DD'),7,1474,'El Chavo del Ocho');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (56570,'Outlander','US','[18-10765]','en','제2차 세계대전, 평범한 간호사가 알 수 없는 힘으로 18세기 스코틀랜드 중세시대로 타임슬립하면서 겪는 이야기','/oR0PM7hFDqY3kO12cLLQMKiJt8I.jpg',to_date('14/08/09','RR/MM/DD'),8,2083,'아웃랜더');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1516,'The A-Team','US','[10759]','en',null,'/iJsueZM8TqQzeB55tol4mnyQzb9.jpg',to_date('83/01/23','RR/MM/DD'),7,696,'A 특공대');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (92685,'The Owl House','US','[16-10765-35-10759]','en','판타지 세상에 심취해 있는 소녀 루스, 픽션과 현실을 구분하지 못 하고 학교에서 사고를 치다 결국 여름방학 3개월을 정신안정 캠프에서 보내는 처벌을 받게 된다. 하지만 캠프로 떠나기 직전, 우연히 자신의 소설책을 들고 낡은 폐가로 들어가는 부엉이를 뒤쫒다 그토록 동경하던 판타지 세계에서 마녀 이다와 만나게 되는데...','/f3Dd784YEpaWaJUyRCkhiaKxgB0.jpg',to_date('20/01/10','RR/MM/DD'),8,1083,'아울 하우스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (5451,'Sin Senos no hay Paraíso','CO','[10759-18]','es',null,'/pSsQ5rFalyT7ehwgeSlITgBSi5S.jpg',to_date('08/06/16','RR/MM/DD'),7,815,'Sin Senos no hay Paraíso');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (12225,'Peppa Pig','GB','[16-10762]','en','페파 피그는 엄마, 아빠, 그리고 남동생 조지와 함께 사는 활기찬 돼지입니다. 그녀는 진흙 웅덩이에 뛰어드는 것과 큰 코웃음 소리를 내는 것을 좋아합니다.','/aTaGTqkbMWoy0ef0M48qJkMltxE.jpg',to_date('04/05/31','RR/MM/DD'),0,0,'페파 피그');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (1398,'The Sopranos','US','[18]','en','1999년 1월 HBO에서 방영을 시작한 마피아 범죄물. 뉴저지 마피아의 중간 보스인 토니 소프라노는 이유를 알 수 없는 공황발작으로 정신과 의사를 찾게 된다. 토니는 아내 카멜라와 두 자녀를 부양하는 평범한 아버지로서의 생활과 마피아로서의 생활을 동시에 진행하면서 정신적 공황을 겪게 되고 이에 대한 상담은 필연적으로 마피아 내부의 범죄행위를 노출하는 결과를 가져온다. 마피아 조직의 중간 보스에 걸맞지 않은 정신적 나약함으로 비추어 질 수 있다는 점과 누군가에게 조직의 비밀을 발설하고 있다는 사실이 지닌 위험 때문에 상담은 비밀리에 진행되는데...','/lXaipuB4DrTfbyGT2xN9IpDtNH.jpg',to_date('99/01/10','RR/MM/DD'),8,1756,'소프라노스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (114156,'Érase una vez... Pero ya no','ES','[10765]','es','어쩔 수 없이 헤어져야 했던 커플. 이제 다른 생에서 서로를 찾아 마을에 내려진 저주를 풀어야 한다. 아무도 사랑에 빠지지 못하는 저주를.','/x9nxavlkJZjpy3txyytKu1IoGVd.jpg',to_date('22/03/11','RR/MM/DD'),7,13,'옛날 옛적에... 그리고 지금은');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (92967,'Mucize Doktor','TR','[18]','tr',null,'/ypfoiA298wMAOVPTkB73xJtKTG5.jpg',to_date('19/09/12','RR/MM/DD'),8,802,'무지제 도크토르');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (80318,'CentoVetrine','Unknown','[10766-18]','it',null,'/25v6iDGmIpyG3zndfYdt4KfQgQ9.jpg',to_date('01/01/08','RR/MM/DD'),6,1,'CentoVetrine');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (93740,'Foundation','US','[10765-18]','en','아이작 아시모프의 소설 원작. 은하 제국의 멸망이 다가오자, 인류를 구하고 문명을 재건하기 위해 나선 망명자들의 장대한 여정을 그린다.','/4StTTWsS0MBGL8JMH1JD1VwdNWJ.jpg',to_date('21/09/23','RR/MM/DD'),8,590,'파운데이션');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (93149,'プランダラ','JP','[10759-10765-16]','ja','''폐기전쟁''이라는 미증유의 대 전쟁이 일어난 후의 세계 아르시아.

그곳은 강자가 약자로부터 자신들의 존재를 나타내는 ''카운트''를 빼앗는 약육강식의 세계였다.

그런 세계에서 두 사람은 만났다.

가면으로 본성을 감추지만 야한 것을 제일 좋아하고 약한 자들을 위해서 태도를 휘두르는 청년 리히트.

어머니의 유언에 의지해 ''전설의 격추왕''을 찾아서 여행하는 씩씩하고 한결같은 소녀 히나.

둘의 만남을 계기로

''카운트''가 모든 것을 지배하는 세계의 수수께끼가 조금씩 밝혀져 간다--','/cp1iGqNNy5JRhWbpP3qoANgz1gV.jpg',to_date('20/01/09','RR/MM/DD'),8,646,'플런더러');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (130237,'阿波連さんははかれない','JP','[16-35]','ja','몸집이 작고 조용한 여자아이, 아하렌 레이나 양.

다른 사람과의 거리 조절이 조금 서툴다.

그런 그녀의 옆자리에 앉은 라이도는

아하렌 양과의 사이에서 거리감을 느끼고 있었다.

어느 날, 아하렌 양이 떨어뜨린 지우개를

라이도가 주워 준 것을 계기로 둘 사이의 거리는 갑자기 가까워지는데?!

''너무 멀었다가'' ''너무 가까웠다가'' 예측 불가능한 아하렌 양.

여러 가지 의미로, ''알 수 없는'' 밀착 계열?

청춘 러브 코미디의 막이 오른다!!','/oR0ZIrFv84lbv4hhoyszx1IMnJE.jpg',to_date('22/04/02','RR/MM/DD'),6,11,'아하렌 양은 알 수가 없어');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (67136,'This Is Us','US','[35-18]','en','같은 날 태어난 사람들의 이야기로 출산을 앞둔 커플인 잭과 레베카, 텔레비전 배우 케빈, 비만과 싸우는 케이트, 그리고 낳아준 부모를 찾는 랜달의 이야기.','/9oYpkVSbjX8TXifdAW0a5ek8XsW.jpg',to_date('16/09/20','RR/MM/DD'),8,1109,'디스 이즈 어스');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (60585,'Bosch','US','[9648-18-80]','en','베테랑 강력반 형사 해리 보쉬는 수사를 하던 중 과실치사 혐의로 재판을 받게 되고 휴직을 하게 된다. 어느 날 힐즈에서 신원 미상 아이의 뼈가 발견된 후 사건 현장에 도착한 해리는 상관의 휴직 명령을 무시하면서 본격적인 수사를 하게된다.','/1DhhUJnHcuGG7NhEbXW3t34OVr8.jpg',to_date('15/01/14','RR/MM/DD'),8,344,'보슈');
Insert into ADMIN.K_SHOWS (ID,ORIGINAL_NAME,ORIGINAL_COUNTRY,GENRE_IDS,ORIGINAL_LANGUAGE,OVERVIEW,POSTER_PATH,FIRST_AIR_DATE,VOTE_AVERAGE,VOTE_COUNT,NAME) values (76773,'Station 19','US','[18-10759]','en','그레이 아나토미의 스핀오프 드라마로, 스테이션 19에서 근무하는 소방관들을 주인공으로 하는 이야기','/dxSNlmw6HMtjeCNAoDpnuY8y3bY.jpg',to_date('18/03/22','RR/MM/DD'),8,1136,'스테이션 19');
--------------------------------------------------------
--  DDL for Index PK_K_SHOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_K_SHOWS" ON "ADMIN"."K_SHOWS" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table K_SHOWS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("ORIGINAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("ORIGINAL_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("GENRE_IDS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("POSTER_PATH" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."K_SHOWS" ADD CONSTRAINT "PK_K_SHOWS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."K_SHOWS" MODIFY ("NAME" NOT NULL ENABLE);
